# Generated by Django 3.2 on 2021-04-24 15:48

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=items.models.generate_unique_item_id, max_length=8, unique=True),
        ),
    ]
