# Generated by Django 3.2 on 2021-04-24 15:48

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default=orders.models.generate_unique_order_num, max_length=8, unique=True),
        ),
    ]
