# Generated by Django 3.2 on 2021-04-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ship_address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ship_address2',
        ),
    ]
