# Generated by Django 3.2 on 2021-04-23 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='username',
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='ship_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
