# Generated by Django 3.2 on 2021-04-24 15:48

from django.db import migrations, models
import shipments.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20210423_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='ship_id',
            field=models.CharField(default=shipments.models.generate_unique_ship_id, max_length=8, unique=True),
        ),
    ]
