# Generated by Django 3.2 on 2021-04-22 01:24

from django.db import migrations, models
import django.db.models.deletion
import orderitems.modelFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', orderitems.modelFields.IntegerRangeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
